worker_processes auto;

events {
    worker_connections 4096;
}

http {
    # 부하를 분산시킬 서버 그룹 정의
    upstream ticketeam_backend {
        least_conn;
        server app:8080;
    }

    # 애플리케이션 서버 (80 포트)
    server {
        listen 80;
        location / {
            proxy_pass http://ticketeam_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Prometheus UI (9090 포트)
    server {
        listen 9090;
        location / {
            proxy_pass http://prometheus:9090;
        }
    }

    # Grafana UI (3000 포트)
    server {
        listen 3000;
        location / {
             proxy_set_header Host $http_host; # $host 대신 $http_host 사용
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
             proxy_set_header X-Frame-Options SAMEORIGIN;
            proxy_pass http://grafana:3000;
        }
    }
}